#!/usr/bin/env bash
# One-command setup for the Swarm Scan Blender addon on Linux.
#
# Run this immediately after cloning the repo, no prior build step needed:
#
#   ./setup_linux.sh
#
# It does everything:
#   1. Installs Blender 5.2.0 into ~/blender (skips if already there)
#   2. Makes the Swarm Scan addon load automatically EVERY time Blender opens
#   3. Adds a `blender` command and an app-menu icon
#   4. Verifies the addon loaded, then tells you how to open it
set -euo pipefail

BVER="5.2.0"
BDIR="$HOME/blender"
BIN="$BDIR/blender"
TARBALL="blender-${BVER}-linux-x64.tar.xz"
URL="https://download.blender.org/release/Blender5.2/${TARBALL}"

# The repo root is where this script lives (git clone root).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADDON_DIR="$REPO_ROOT/blender_addon"

say()  { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
fail() { printf '\n\033[31mERROR: %s\033[0m\n' "$1" >&2; exit 1; }

[ -f "$ADDON_DIR/dev_load.py" ] \
  || fail "blender_addon/ not found. Make sure you're at the repo root."

# --- 1. Blender ------------------------------------------------------------
if [ -x "$BIN" ] && "$BIN" --version 2>/dev/null | grep -q "Blender ${BVER}"; then
  say "Blender ${BVER} already installed at $BIN — skipping download."
else
  say "Installing Blender ${BVER} into $BDIR ..."
  cd "$HOME"
  if [ ! -f "$TARBALL" ]; then
    command -v wget >/dev/null 2>&1 && wget -q --show-progress "$URL" \
      || curl -fL -o "$TARBALL" "$URL" \
      || fail "could not download Blender (no working wget/curl, or no internet)."
  fi
  tar -xf "$TARBALL"
  rm -rf "$BDIR"
  mv "blender-${BVER}-linux-x64" "$BDIR"
  "$BIN" --version | head -1
fi

# --- 2. auto-load on every launch -----------------------------------------
say "Setting up automatic addon loading ..."
SCRIPTS="$("$BIN" -b --factory-startup --python-expr \
  "import bpy;print('SCRIPTS='+bpy.utils.user_resource('SCRIPTS'))" 2>/dev/null \
  | sed -n 's/^SCRIPTS=//p' | head -1)"
[ -n "$SCRIPTS" ] || fail "could not determine Blender's scripts folder."
STARTUP="$SCRIPTS/startup"
mkdir -p "$STARTUP"
# Clear any stale compiled copy so a re-run at a new location can't load an
# orphaned .pyc pointing at the old path (Blender will import cached bytecode).
rm -f "$STARTUP"/__pycache__/swarm_scan_autoload*.pyc 2>/dev/null || true

cat > "$STARTUP/swarm_scan_autoload.py" <<PY
# Auto-generated by setup_linux.sh -- loads Swarm Scan on every Blender launch.
# Do not move the folder below; re-run setup_linux.sh if you relocate it.
import os, sys
ADDON_DIR = "$ADDON_DIR"
REPO_ROOT = os.path.dirname(ADDON_DIR)

def register():
    for p in (REPO_ROOT, ADDON_DIR):
        if p not in sys.path:
            sys.path.insert(0, p)
    import swarm_scanner
    swarm_scanner.register()

def unregister():
    import swarm_scanner
    swarm_scanner.unregister()
PY
echo "  wrote $STARTUP/swarm_scan_autoload.py"

# --- 3. `blender` command + app-menu icon ---------------------------------
mkdir -p "$HOME/.local/bin"
ln -sf "$BIN" "$HOME/.local/bin/blender"
APPS="$HOME/.local/share/applications"
mkdir -p "$APPS"
cat > "$APPS/swarm-scan-blender.desktop" <<DESKTOP
[Desktop Entry]
Name=Blender (Swarm Scan)
Comment=Blender with the Swarm Scan addon auto-loaded
Exec=$BIN
Icon=blender
Terminal=false
Type=Application
Categories=Graphics;
DESKTOP
update-desktop-database "$APPS" >/dev/null 2>&1 || true
echo "  added 'blender' command and a 'Blender (Swarm Scan)' menu icon"

# --- 4. verify -------------------------------------------------------------
say "Verifying the addon loads ..."
# Reliable check: the registered panel/operator types appear in bpy.types.
# Do NOT use hasattr(bpy.ops.swarm, ...) -- bpy.ops always fabricates a proxy.
if "$BIN" -b --python-expr "import bpy;print('CHECK:'+str(hasattr(bpy.types,'SWARM_PT_panel')))" 2>/dev/null | grep -q "CHECK:True"; then
  echo "  OK — Swarm Scan loads automatically."
else
  fail "the addon did not register. Re-run this script, or ask for help."
fi

cat <<DONE

============================================================
  DONE. Everything is installed.

  To open it, do ANY of these:
    - type:        ~/blender/blender
    - or type:     blender        (after you log out and back in once)
    - or click:    "Blender (Swarm Scan)" in your applications menu

  When Blender opens, the addon is ALREADY loaded:
    move the mouse over the 3D view, press  N , and click the
    "Swarm Scan" tab on the right.

  Optional post-setup checks:
    python3 linux_quickstart/check_env.py
============================================================
DONE
